package com.example.showcase.githubapi.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.showcase.githubapi.data.db.RepoDb;

import com.example.showcase.githubapi.data.db.RepoDbDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig repoDbDaoConfig;

    private final RepoDbDao repoDbDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        repoDbDaoConfig = daoConfigMap.get(RepoDbDao.class).clone();
        repoDbDaoConfig.initIdentityScope(type);

        repoDbDao = new RepoDbDao(repoDbDaoConfig, this);

        registerDao(RepoDb.class, repoDbDao);
    }
    
    public void clear() {
        repoDbDaoConfig.clearIdentityScope();
    }

    public RepoDbDao getRepoDbDao() {
        return repoDbDao;
    }

}
