package com.razeeman.showcase.githubapi.data.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "repo".
*/
public class RepoDbDao extends AbstractDao<RepoDb, Long> {

    public static final String TABLENAME = "repo";

    /**
     * Properties of entity RepoDb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "name");
        public final static Property Owner_login = new Property(2, String.class, "owner_login", false, "owner_login");
        public final static Property Html_url = new Property(3, String.class, "html_url", false, "html_url");
        public final static Property Description = new Property(4, String.class, "description", false, "description");
        public final static Property Url = new Property(5, String.class, "url", false, "url");
        public final static Property Stargazers_count = new Property(6, int.class, "stargazers_count", false, "stargazers_count");
        public final static Property Language = new Property(7, String.class, "language", false, "language");
        public final static Property Forks_count = new Property(8, int.class, "forks_count", false, "forks_count");
    }


    public RepoDbDao(DaoConfig config) {
        super(config);
    }
    
    public RepoDbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"repo\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"name\" TEXT," + // 1: name
                "\"owner_login\" TEXT," + // 2: owner_login
                "\"html_url\" TEXT," + // 3: html_url
                "\"description\" TEXT," + // 4: description
                "\"url\" TEXT," + // 5: url
                "\"stargazers_count\" INTEGER NOT NULL ," + // 6: stargazers_count
                "\"language\" TEXT," + // 7: language
                "\"forks_count\" INTEGER NOT NULL );"); // 8: forks_count
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"repo\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RepoDb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String owner_login = entity.getOwner_login();
        if (owner_login != null) {
            stmt.bindString(3, owner_login);
        }
 
        String html_url = entity.getHtml_url();
        if (html_url != null) {
            stmt.bindString(4, html_url);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(5, description);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
        stmt.bindLong(7, entity.getStargazers_count());
 
        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(8, language);
        }
        stmt.bindLong(9, entity.getForks_count());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RepoDb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String owner_login = entity.getOwner_login();
        if (owner_login != null) {
            stmt.bindString(3, owner_login);
        }
 
        String html_url = entity.getHtml_url();
        if (html_url != null) {
            stmt.bindString(4, html_url);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(5, description);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
        stmt.bindLong(7, entity.getStargazers_count());
 
        String language = entity.getLanguage();
        if (language != null) {
            stmt.bindString(8, language);
        }
        stmt.bindLong(9, entity.getForks_count());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RepoDb readEntity(Cursor cursor, int offset) {
        RepoDb entity = new RepoDb( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // owner_login
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // html_url
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // description
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // url
            cursor.getInt(offset + 6), // stargazers_count
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // language
            cursor.getInt(offset + 8) // forks_count
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RepoDb entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setOwner_login(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setHtml_url(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDescription(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStargazers_count(cursor.getInt(offset + 6));
        entity.setLanguage(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setForks_count(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RepoDb entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RepoDb entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RepoDb entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
